==== Burn

`Burn` indicates an action of burning collectible assets.

When a user burns collectible assets, the protocol will convert and record it as Burn metadata following the interface below.

===== Interface

[,typescript]
----
interface Burn {
    address?: string;
    id?: string;
    name?: string;
    standard?: string;
    symbol?: string;
    value: string;
    uri?: string;
    parsed_image_url?: string;
}
----

===== Description

|===
| Field               | Description

| `address`           | *Optional.* The token address of the burnt collectible assets.
| `id`                | *Optional.* The token ID of the burnt collectible assets.
| `name`              | *Optional.* The token name of the burnt collectible assets.
| `standard`          | *Optional.* The token standard of the burnt collectible assets.
| `symbol`            | *Optional.* The token symbol of the burnt collectible assets.
| `value`             | *Required.* The token amount/value of the burnt collectible assets.
| `uri`               | *Optional.* The token URI of the burnt collectible assets.
| `parsed_image_url`  | *Optional.* The parsed image URL of the burnt collectible assets.
|===

===== Example

[,json]
----
{
    "address": "0x889edC2eDab5f40e902b864aD4d7AdE8E412F9B1",
    "id": "1685",
    "value": "1",
    "name": "Lido: stETH Withdrawal NFT",
    "symbol": "unstETH",
    "standard": "ERC-721"
}
----
