===== Revoke

`Revoke` indicates an action of removing permissions to assets.

When a user revokes permissions to assets, the protocol will convert and record it as Revoke metadata following the interface below.

===== Interface

[,typescript]
----
interface Revoke {
    action: string;
    address?: string;
    id?: string;
    value?: string;
    name?: string;
    symbol?: string;
    uri?: string;
    decimals?: number;
    standard?: string;
}
----

===== Description

|===
| Field               | Description

| `action`            | *Required.* The action of removing permissions to assets.
| `address`           | *Optional.* The token address of the revoked assets.
| `id`                | *Optional.* The token ID of the revoked assets.
| `name`              | *Optional.* The token name of the revoked assets.
| `standard`          | *Optional.* The token standard of the revoked assets.
| `symbol`            | *Optional.* The token symbol of the revoked assets.
| `value`             | *Required.* The token amount/value of the revoked assets.
| `uri`               | *Optional.* The token URI of the revoked assets.
| `decimals`          | *Optional.* The token decimals of the revoked assets.
|===

===== Example

[,json]
----
{
    "action": "revoke",
    "address": "0x72e4f9F808C49A2a61dE9C5896298920Dc4EEEa9",
    "id": "6",
    "value": "100000000000",
    "name": "HarryPotterObamaSonic10Inu",
    "symbol": "BITCOIN",
    "uri": "https://assets.coingecko.com/coins/images/30323/thumb/hpos10i_logo_casino_night-dexview.png?1696529224",
    "decimals": 8,
    "standard": "ERC-20"
}
----