==== Stake

`Stake` indicates the action of staking token(s).

===== Interface

[,typescript]
----
interface Stake {
    action: string;
    token: {
        address?: string;
        value: string;
        name?: string;
        symbol?: string;
        decimals?: string;
        standard?: string;
    };
    period?: {
        start: Date,
        end: Date,
    }
}
----

===== Fields

`action` *Required*:: Action of the staking transaction, e.g. `stake`.
`tokens` *Required*:: Array of tokens staked from the staking pool.
`tokens.address` *Optional*:: Contract address of the staked token.
If the token is a native token, this field is not required, e.g. `0xc98D64DA73a6616c42117b582e832812e7B8D57F`.
`tokens.value` *Required*:: Amount of the staked token, e.g. `5764251642130434218884`.
`tokens.name` *Optional*:: Name of the staked token, e.g. `RSS3`.
`tokens.symbol` *Optional*:: Symbol of the staked token, e.g. `RSS3`.
`tokens.decimals` *Optional*:: Decimals of the staked token, e.g. `18`.
`tokens.standard` *Optional*:: Standard of the staked token, e.g. `ERC-20`.
`period` *Optional*:: Period of the staking (if the staking has a time locker).
`period.start` *Required*:: Start time of the staking period, e.g. `2023-02-02T12:26:59Z`.
`period.end` *Required*:: End time of the staking period, e.g. `2023-05-03T12:26:59Z`.

===== Example

[,json]
----
{
  "action": "stake",
  "token": {
    "address": "0xc98D64DA73a6616c42117b582e832812e7B8D57F",
    "value": "5931560000000000000000",
    "name": "RSS3",
    "symbol": "RSS3",
    "decimals": 18,
    "standard": "ERC-20"
  },
  "period": {
    "start": "2023-02-02T12:26:59Z",
    "end": "2023-05-03T12:26:59Z"
  }
}
----
