==== Mint

`Mint` indicates an action of minting collectible assets.

When a user mints collectible assets, the protocol will convert and record it as Mint metadata following the interface below.

===== Interface

[,typescript]
----
interface Mint {
    address?: string;
    id?: string;
    name?: string;
    standard?: string;
    symbol?: string;
    value: string;
    uri?: string;
    parsed_image_url?: string;
}
----

===== Description

|===
| Field               | Description

| `address`           | *Optional.* The token address of the minted collectible assets.
| `id`                | *Optional.* The token ID of the minted collectible assets.
| `name`              | *Optional.* The token name of the minted collectible assets.
| `standard`          | *Optional.* The token standard of the minted collectible assets.
| `symbol`            | *Optional.* The token symbol of the minted collectible assets.
| `value`             | *Required.* The token amount/value of the minted collectible assets.
| `uri`               | *Optional.* The token URI of the minted collectible assets.
| `parsed_image_url`  | *Optional.* The parsed image URL of the minted collectible assets.
|===

===== Example

[,json]
----
{
    "address": "0xFC19B4536a4b9B9EEc1C362894f7dC505457538D",
    "id": "696",
    "value": "1",
    "name": "R3FUS3",
    "symbol": "R3FUS3",
    "uri": "https://highlight-creator-assets.highlight.xyz/main/base-dir/b0b61e2c-f741-48c4-94ca-f090c9f5817e/onChainDir/696",
    "standard": "ERC-721"
}
----
