==== Transfer

`Transfer` indicates the action of transfering in-game item to others.

===== Interface

[,typescript]
----
interface Transfer {
    address?: string;
    id?: string;
    name?: string;
    standard?: string;
    symbol?: string;
    value: string;
    uri?: string;
    parsed_image_url?: string;
}
----

===== Fields

`address` *Optional*:: Address of the transferred metaverse token, e.g. `0x5452C7fB99D99fAb3Cc1875E9DA9829Cb50F7A13`.
`id` *Optional*:: ID of the transferred metaverse token, e.g. `1032`.
`name` *Optional*:: Name of the transferred metaverse token, e.g. `The Genesis RSS3 Avatar NFT`.
`standard` *Optional*:: Standard of the transferred metaverse token, e.g. `ERC-721`.
`symbol` *Optional*:: Symbol of the transferred metaverse token, e.g. `The Genesis RSS3 Avatar NFT`.
`value` *Required*:: Amount/value of the transferred metaverse token, e.g. `1`.
`uri` *Optional*:: URI of the transferred metaverse token, e.g. `ipfs://QmdHTECGDf8u4vNe4PLXSqBTBkYqxiCaYYfdJiUhtgiBKR/6`.
`parsed_image_url` *Optional*:: The parsed image URL of the transferred metaverse token, e.g. `https://ipfs.io/ipfs/QmdHTECGDf8u4vNe4PLXSqBTBkYqxiCaYYfdJiUhtgiBKR/6.png`.

===== Example

[,json]
----
{
    "address": "0x385Eeac5cB85A38A9a07A70c73e0a3271CfB54A7",
    "decimals": 18,
    "name": "Aavegotchi GHST Token (PoS)",
    "standard": "ERC-20",
    "symbol": "GHST",
    "value": "50000000000000000"
}
----
