===== Deposit

`Deposit` indicates an action of depositing assets from one network to another.

When a user deposits assets from one network to another, the protocol will convert and record it as Deposit metadata following the interface below.

===== Interface

[,typescript]
----
interface Deposit {
    action: string;
    source_network: string;
    target_network: string;
    token: {
        address?: string;
        id?: string;
        value: string;
        name?: string;
        symbol?: string;
        uri?: string;
        decimals?: number;
        standard?: string;
    }
}
----

===== Description

|===
| Field               | Description

| `action`            | *Required.* The action of depositing assets from one network to another.
| `source_network`    | *Required.* The source network from which the tokens are deposited.
| `target_network`    | *Required.* The target network to which the tokens are deposited.
| `token`             | *Required.* Details of the deposited token.
| `token.address`     | *Optional.* The token address of the deposited token.
| `token.id`          | *Optional.* The token ID of the deposited token.
| `token.value`       | *Required.* The token value of the deposited token.
| `token.name`        | *Optional.* The token name of the deposited token.
| `token.symbol`      | *Optional.* The token symbol of the deposited token.
| `token.uri`         | *Optional.* The token URI of the deposited token.
| `token.decimals`    | *Optional.* The token decimal of the deposited token.
| `token.standard`    | *Optional.* The token standard of the deposited token.
|===

===== Example

[,json]
----
{
  "action": "deposit",
  "source_network": "ethereum",
  "target_network": "ethereum",
  "token": {
    "address": "0x23b891e5C62E0955ae2bD185990103928Ab817b3",
    "value": "84265385201993306272353",
    "name": "nUSD",
    "symbol": "nUSD",
    "decimals": 18,
    "standard": "ERC-20"
  }
}
----