==== Comment

`Comment` indicates an action of commenting on an existing post.

When a user comments on an existing post, the protocol will convert and record it as Comment metadata following the interface below.

===== Interface

[,typescript]
----
interface Comment {
    handle?: string
    body?: string
    title?: string
    summary?: string
    media?: {
        address: string
        mime_type: string
    }[]
    tags?: string[]
    author_url?: string
    profile_id?: string
    publication_id?: string
    content_uri?: string
    timestamp?: number
    target: {
        handle?: string
        body?: string
        title?: string
        summary?: string
        media?: {
            address: string
            mime_type: string
        }[]
        tags?: string[]
        author_url?: string
        profile_id?: string
        publication_id?: string
        content_uri?: string
    }
}
----

===== Description

|===
| Field               | Description

| `handle`            | *Optional.* The handle/username of the user who is commenting.
| `body`              | *Optional.* The main content of the comment.
| `title`             | *Optional.* The title of the comment.
| `summary`           | *Optional.* A short summary of the comment.
| `media`             | *Optional.* An array of media objects that are attached to the comment.
| `media.address`     | *Required.* The url/address of the media object.
| `media.mime_type`   | *Required.* The mime type of the media object.
| `tags`              | *Optional.* An array of tags that the comment belongs to.
| `author_url`        | *Optional.* The url of the author.
| `profile_id`        | *Optional.* The profile ID of the author.
| `publication_id`    | *Optional.* The publication ID of the comment.
| `content_uri`       | *Optional.* The content URI of the comment.
| `timestamp`         | *Optional.* The timestamp of the comment.
| `target`            | *Required.* The target post being commented on.
| `target.handle`     | *Optional.* The handle/username of the user who created the original post.
| `target.body`       | *Optional.* The main content of the original post.
| `target.title`      | *Optional.* The title of the original post.
| `target.summary`    | *Optional.* A short summary of the original post.
| `target.media`      | *Optional.* An array of media objects that are attached to the original post.
| `target.media.address` | *Required.* The url/address of the media object.
| `target.media.mime_type` | *Required.* The mime type of the media object.
| `target.tags`       | *Optional.* An array of tags that the original post belongs to.
| `target.author_url` | *Optional.* The url of the author of the original post.
| `target.profile_id` | *Optional.* The profile ID of the author of the original post.
| `target.publication_id` | *Optional.* The publication ID of the original post.
| `target.content_uri` | *Optional.* The content URI of the original post.
|===

===== Example

[,json]
----
{
    "handle": "romain_millon.lens",
    "body": "You are not far, soon ahead...",
    "profile_id": "0x01ce63",
    "publication_id": "0x73",
    "content_uri": "ar://snYKMd1W5Hzp6Q4qkC-InfSzEVWZDx39M_7MuY4Rld4",
    "timestamp": 1699341732,
    "target": {
        "handle": "jessyjeanne.lens",
        "body": "Jessy is a queen.you want it or not. 👸🏻🍟🙊 \n\nI feel Fakemous being in the top 3 key with highest price value after @lens/stani \n\nIt gives me Britney b*tch vibes 😍😂🍟",
        "media": [
            {
                "address": "ipfs://QmT5tE8WeLYgjCkxJwJHAdw9HtkiAGWRuUKEGKkQwtLkat",
                "mime_type": "image/jpeg"
            }
        ],
        "profile_id": "0x73b1",
        "publication_id": "0x3d81",
        "content_uri": "ar://ggN86IfdpZL15nln0Zk3kLWVVt3lnxZOL2REaRhD9Qs"
    }
}
----