==== Buy

`Buy` indicates an action of buying collectible assets.

When a user buys collectible assets, the protocol will convert and record it as Buy metadata following the interface below.

===== Interface

[,typescript]
----
interface Buy {
    action: string;
    address?: string;
    id?: string;
    name?: string;
    standard?: string;
    symbol?: string;
    value: string;
    uri?: string;
    parsed_image_url?: string;
    cost: {
        name?: string;
        symbol?: string;
        decimals?: number;
        value: string;
        address?: string;
        standard?: string;
    };
}
----

===== Description

|===
| Field               | Description

| `action`            | *Required.* The action of buying collectible assets.
| `address`           | *Optional.* The token address of the bought collectible assets.
| `id`                | *Optional.* The token ID of the bought collectible assets.
| `name`              | *Optional.* The token name of the bought collectible assets.
| `standard`          | *Optional.* The token standard of the bought collectible assets.
| `symbol`            | *Optional.* The token symbol of the bought collectible assets.
| `value`             | *Required.* The token amount/value of the bought collectible assets.
| `uri`               | *Optional.* The token URI of the bought collectible assets.
| `parsed_image_url`  | *Optional.* The parsed image URL of the bought collectible assets.
| `cost`              | *Required.* The cost details of the buying action.
| `cost.name`         | *Optional.* The token name of the cost token.
| `cost.symbol`       | *Optional.* The token symbol of the cost token.
| `cost.decimals`     | *Optional.* The token decimal places of the cost token.
| `cost.value`        | *Required.* The token amount/value of the cost token.
| `cost.address`      | *Optional.* The token address of the cost token.
| `cost.standard`     | *Optional.* The token standard of the cost token.
|===

===== Example

[,json]
----
{
    "action": "buy",
    "address": "0x74EE68a33f6c9f113e22B3B77418B75f85d07D22",
    "id": "5",
    "value": "1",
    "name": "Zerion Genesis Collection",
    "symbol": "ZGC",
    "uri": "ipfs://QmXBUGFTXuAeBfK9oB9G1NAhGq7AwosWjHFRHMdahETeRK",
    "standard": "ERC-1155",
    "cost": {
        "value": "14525000000000000",
        "name": "Ethereum",
        "symbol": "ETH",
        "decimals": 18
    }
}
----
