==== Sell

`Sell` indicates an action of selling collectible assets.

When a user sells collectible assets, the protocol will convert and record it as Sell metadata following the interface below.

===== Interface

[,typescript]
----
interface Sell {
    action: string;
    address?: string;
    id?: string;
    name?: string;
    standard?: string;
    symbol?: string;
    value: string;
    uri?: string;
    parsed_image_url?: string;
    cost: {
        name?: string;
        symbol?: string;
        decimals?: number;
        value: string;
        address?: string;
        standard?: string;
    };
}
----

===== Description

|===
| Field               | Description

| `action`            | *Required.* The action of selling collectible assets.
| `address`           | *Optional.* The token address of the sold collectible assets.
| `id`                | *Optional.* The token ID of the sold collectible assets.
| `name`              | *Optional.* The token name of the sold collectible assets.
| `standard`          | *Optional.* The token standard of the sold collectible assets.
| `symbol`            | *Optional.* The token symbol of the sold collectible assets.
| `value`             | *Required.* The token amount/value of the sold collectible assets.
| `uri`               | *Optional.* The token URI of the sold collectible assets.
| `parsed_image_url`  | *Optional.* The parsed image URL of the sold collectible assets.
| `cost`              | *Required.* The cost details of the buying action.
| `cost.name`         | *Optional.* The token name of the cost token.
| `cost.symbol`       | *Optional.* The token symbol of the cost token.
| `cost.decimals`     | *Optional.* The token decimal places of the cost token.
| `cost.value`        | *Required.* The token amount/value of the cost token.
| `cost.address`      | *Optional.* The token address of the cost token.
| `cost.standard`     | *Optional.* The token standard of the cost token.
|===

===== Example

[,json]
----
{
    "action": "sell",
    "address": "0x306b1ea3ecdf94aB739F1910bbda052Ed4A9f949",
    "id": "159",
    "value": "1",
    "name": "Beanz",
    "symbol": "BEANZ",
    "uri": "ipfs://QmdYeDpkVZedk1mkGodjNmF35UNxwafhFLVvsHrWgJoz6A/beanz_metadata/159",
    "standard": "ERC-721",
    "cost": {
        "address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
        "value": "10500000000000000",
        "name": "Wrapped Ether",
        "symbol": "WETH",
        "decimals": 18,
        "standard": "ERC-20"
    }
}
----
