==== Sell

`Sell` indicates the action of selling token(s).

===== Interface

[,typescript]
----
interface Sell {
    action: string;
    address?: string;
    id?: string;
    name?: string;
    standard?: string;
    symbol?: string;
    value: string;
    uri?: string;
    parsed_image_url?: string;
    cost: {
        name?: string;
        symbol?: string;
        decimals?: number;
        value: string;
        address?: string;
        standard?: string;
    };
}
----

===== Fields

`action` *Required*:: Action of selling collectible token, e.g. `sell`.
`address` *Optional*:: Address of the sold collectible token, e.g. `0x306b1ea3ecdf94aB739F1910bbda052Ed4A9f949`.
`id` *Optional*:: ID of the sold collectible token, e.g. `159`.
`name` *Optional*:: Name of the sold collectible token, e.g. `Beanz`.
`standard` *Optional*:: Standard of the sold collectible token, e.g. `ERC-721`.
`symbol` *Optional*:: Symbol of the sold collectible token, e.g. `BEANZ`.
`value` *Required*:: Amount of the sold collectible token, e.g. `1`.
`uri` *Optional*:: URI of the sold collectible token, e.g. `ipfs://QmdYeDpkVZedk1mkGodjNmF35UNxwafhFLVvsHrWgJoz6A/beanz_metadata/159`.
`parsed_image_url` *Optional*:: Parsed image URL of the sold collectible token, e.g. `https://ipfs.io/ipfs/QmdYeDpkVZedk1mkGodjNmF35UNxwafhFLVvsHrWgJoz6A/beanz_metadata/159`.
`cost` *Required*:: Cost of the sold collectible token. Should include the following fields.
`cost.name` *Optional*:: Name of the cost token, e.g. `Wrapped Ether`.
`cost.symbol` *Optional*:: Symbol of the cost token, e.g. `WETH`.
`cost.decimals` *Optional*:: Decimal places of the cost token, e.g. `18`.
`cost.value` *Required*:: Amount of the cost token, e.g. `10500000000000000`.
`cost.address` *Optional*:: Address of the cost token. If the token is a native token, this field is not required, e.g. `0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2`.
`cost.standard` *Optional*:: Standard of the cost token, e.g. `ERC-20`.

===== Example

[,json]
----
{
    "action": "sell",
    "address": "0x306b1ea3ecdf94aB739F1910bbda052Ed4A9f949",
    "id": "159",
    "value": "1",
    "name": "Beanz",
    "symbol": "BEANZ",
    "uri": "ipfs://QmdYeDpkVZedk1mkGodjNmF35UNxwafhFLVvsHrWgJoz6A/beanz_metadata/159",
    "standard": "ERC-721",
    "cost": {
        "address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
        "value": "10500000000000000",
        "name": "Wrapped Ether",
        "symbol": "WETH",
        "decimals": 18,
        "standard": "ERC-20"
    }
}
----
