==== Transfer

`Transfer` indicates an action of transferring collectible assets to others.

When a user transfers collectible assets to others, the protocol will convert and record it as Transfer metadata following the interface below.

===== Interface

[,typescript]
----
interface Transfer {
    address?: string;
    id?: string;
    name?: string;
    standard?: string;
    symbol?: string;
    value: string;
    uri?: string;
    parsed_image_url?: string;
}
----

===== Description

|===
| Field               | Description

| `address`           | *Optional.* The token address of the transferred collectible assets.
| `id`                | *Optional.* The token ID of the transferred collectible assets.
| `name`              | *Optional.* The token name of the transferred collectible assets.
| `standard`          | *Optional.* The token standard of the transferred collectible assets.
| `symbol`            | *Optional.* The token symbol of the transferred collectible assets.
| `value`             | *Required.* The token amount/value of the transferred collectible assets.
| `uri`               | *Optional.* The token URI of the transferred collectible assets.
| `parsed_image_url`  | *Optional.* The parsed image URL of the transferred collectible assets.
|===

===== Example

[,json]
----
{
    "address": "0x5452C7fB99D99fAb3Cc1875E9DA9829Cb50F7A13",
    "id": "1032",
    "value": "1",
    "name": "The Genesis RSS3 Avatar NFT",
    "symbol": "The Genesis RSS3 Avatar NFT",
    "uri": "data:application/json;base64,eyJuYW1lIjogIlRoZSBHZW5lc2lzIFJTUzMgQXZhdGFyIE5GVCAjMTAzMiIsICJkZXNjcmlwdGlvbiI6ICJUaGUgR2VuZXNpcyBSU1MzIEF2YXRhciBORlQgaXMgYSBjb2xsZWN0aW9uIG9mIDEwLDAwMCB1bmlxdWUgYXZhdGFycyBtZXRpY3Vsb3VzbHkgZGVzaWduZWQgdG8gaWRlbnRpZnkgUlNTMyBjb21tdW5pdHkgbWVtYmVycy4iLCAiaW1hZ2UiOiAiaXBmczovL1FtU1g5UWl3alRHQms1bTIyVXNjVGczdnJiTXdVZkZzbXhWek1INTdoa1BENVUvMTAzMi5wbmcifQ==",
    "standard": "ERC-721"
}
----
