==== Reward

`Reward` indicates an action of rewarding a post or profile.

When a user rewards a post or profile, the protocol will convert and record it as Reward metadata following the interface below.

===== Interface

[,typescript]
----
interface Reward {
    handle?: string
    body?: string
    title?: string
    summary?: string
    media?: {
        address: string
        mime_type: string
    }[]
    tags?: string[]
    author_url?: string
    profile_id?: string
    publication_id?: string
    content_uri?: string
    timestamp?: number
    reward: {
        address?: string
        id?: number
        value: number
        name?: string
        symbol?: string
        uri?: string
        decimals?: number
        standard?: string
    }
}
----

===== Description

|===
| Field             | Description

| `handle`        | *Optional.* The handle/username of the user who is posting.
| `body`          | *Optional.* The main content of the post.
| `title`         | *Optional.* The title of the post.
| `summary`       | *Optional.* A short summary of the post.
| `media`         | *Optional.* An array of media objects that are attached to the post.
| `media.address` | *Required.* The url/address of the media object.
| `media.mime_type` | *Required.* The mime type of the media object.*
| `tags`          | *Optional.* An array of tags that the post belongs to.
| `author_url`    | *Optional.* The url of the author.
| `profile_id`    | *Optional.* The profile ID of the author.
| `publication_id` | *Optional.* The publication ID of the post.
| `content_uri`   | *Optional.* The content URI of the post.
| `timestamp`     | *Optional.* The timestamp of the post.
| `reward`          | *Required.* The reward details.
| `reward.address`  | *Optional.* The address of the reward token.
| `reward.id`       | *Optional.* The ID of the reward token.
| `reward.value`    | *Required.* The amount/value of the reward.
| `reward.name`     | *Optional.* The name of the reward token.
| `reward.symbol`   | *Optional.* The symbol of the reward token.
| `reward.uri`      | *Optional.* The URI of the reward token.
| `reward.decimals` | *Optional.* The decimal places of the reward token.
| `reward.standard` | *Optional.* The standard of the reward token.
|===

===== Example

[,json]
----
{
    "reward": {
        "address": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
        "value": "690000",
        "name": "(PoS) Tether USD",
        "symbol": "USDT",
        "decimals": 6,
        "standard": "ERC-20"
    },
    "target": {
        "handle": "chorsee",
        "title": "Crying with Tama",
        "summary": "The Resonance of the Concert to End Violence Against Women by Chorsee."
    }
}
----