==== Buy

`Buy` indicates an action of buying in-game items.

===== Interface

[,typescript]
----
interface Buy {
  action: string;
  address?: string;
  id?: string;
  name?: string;
  standard?: string;
  symbol?: string;
  value: string;
  uri?: string;
  parsed_image_url?: string;
  cost: {
    name?: string;
    symbol?: string;
    decimals?: number;
    value: string;
    address?: string;
    standard?: string;
  };
}
----

===== Fields

`action` *Required*:: Action of buying metaverse token, e.g. `buy`.
`address` *Optional*:: Address of the bought metaverse token, e.g. `0x74EE68a33f6c9f113e22B3B77418B75f85d07D22`.
`id` *Optional*:: ID of the bought metaverse token, e.g. `5`.
`name` *Optional*:: Name of the bought metaverse token, e.g. `Zerion Genesis Collection`.
`standard` *Optional*:: Standard of the bought metaverse token, e.g. `ERC-1155`.
`symbol` *Optional*:: Symbol of the bought metaverse token, e.g. `ZGC`.
`value` *Required*:: Amount of the bought metaverse token, e.g. `1`.
`uri` *Optional*:: URI of the bought metaverse token, e.g. `ipfs://QmXBUGFTXuAeBfK9oB9G1NAhGq7AwosWjHFRHMdahETeRK`.
`parsed_image_url` *Optional*:: Parsed image URL of the bought metaverse token, e.g. `https://ipfs.io/ipfs/QmXBUGFTXuAeBfK9oB9G1NAhGq7AwosWjHFRHMdahETeRK/image.png`.
`cost` *Required*:: Cost details of the buying action.
`cost.name` *Optional*:: Name of the cost token, e.g. `Ethereum`.
`cost.symbol` *Optional*:: Symbol of the cost token, e.g. `ETH`.
`cost.decimals` *Optional*:: Decimal places of the cost token, e.g. `18`.
`cost.value` *Required*:: Amount of the cost token, e.g. `14525000000000000`.
`cost.address` *Optional*:: Address of the cost token. If the token is a native token, this field is not required, e.g. `0xFC19B4536a4b9B9EEc1C362894f7dC505457538D`.
`cost.standard` *Optional*:: Standard of the cost token, e.g. `ERC-20`.

===== Example

[,json]
----
{
  "action": "buy",
  "address": "0x86935F11C86623deC8a25696E1C19a8659CbF95d",
  "cost": {
  "address": "0x385Eeac5cB85A38A9a07A70c73e0a3271CfB54A7",
    "decimals": 18,
    "name": "Aavegotchi GHST Token (PoS)",
    "standard": "ERC-20",
    "symbol": "GHST",
    "value": "1500000000000000000000"
  },
  "id": "11222",
  "name": "Aavegotchi",
  "standard": "ERC-721",
  "symbol": "GOTCHI",
  "uri": "https://app.aavegotchi.com/metadata/aavegotchis/11222"
}
----
