==== Sell

`Sell` indicates an action of selling in-game items.

===== Interface

[,typescript]
----
interface Sell {
  action: string;
  address?: string;
  id?: string;
  name?: string;
  standard?: string;
  symbol?: string;
  value: string;
  uri?: string;
  parsed_image_url?: string;
  cost: {
    name?: string;
    symbol?: string;
    decimals?: number;
    value: string;
    address?: string;
    standard?: string;
  };
}
----

===== Fields

`action` *Required*:: Action of selling metaverse token, e.g. `sell`.
`address` *Optional*:: Address of the sold metaverse token, e.g. `0x306b1ea3ecdf94aB739F1910bbda052Ed4A9f949`.
`id` *Optional*:: ID of the sold metaverse token, e.g. `159`.
`name` *Optional*:: Name of the sold metaverse token, e.g. `Beanz`.
`standard` *Optional*:: Standard of the sold metaverse token, e.g. `ERC-721`.
`symbol` *Optional*:: Symbol of the sold metaverse token, e.g. `BEANZ`.
`value` *Required*:: Amount of the sold metaverse token, e.g. `1`.
`uri` *Optional*:: URI of the sold metaverse token, e.g. `ipfs://QmdYeDpkVZedk1mkGodjNmF35UNxwafhFLVvsHrWgJoz6A/beanz_metadata/159`.
`parsed_image_url` *Optional*:: Parsed image URL of the sold metaverse token, e.g. `https://ipfs.io/ipfs/QmdYeDpkVZedk1mkGodjNmF35UNxwafhFLVvsHrWgJoz6A/beanz_metadata/159`.
`cost` *Required*:: Cost of the sold metaverse token. Should include the following fields.
`cost.name` *Optional*:: Name of the cost token, e.g. `Wrapped Ether`.
`cost.symbol` *Optional*:: Symbol of the cost token, e.g. `WETH`.
`cost.decimals` *Optional*:: Decimal places of the cost token, e.g. `18`.
`cost.value` *Required*:: Amount of the cost token, e.g. `10500000000000000`.
`cost.address` *Optional*:: Address of the cost token. If the token is a native token, this field is not required, e.g. `0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2`.
`cost.standard` *Optional*:: Standard of the cost token, e.g. `ERC-20`.

===== Example

[,json]
----
{
  "action": "sell",
  "address": "0x86935F11C86623deC8a25696E1C19a8659CbF95d",
  "cost": {
  "address": "0x385Eeac5cB85A38A9a07A70c73e0a3271CfB54A7",
    "decimals": 18,
    "name": "Aavegotchi GHST Token (PoS)",
    "standard": "ERC-20",
    "symbol": "GHST",
    "value": "1500000000000000000000"
  },
  "id": "11222",
  "name": "Aavegotchi",
  "standard": "ERC-721",
  "symbol": "GOTCHI",
  "uri": "https://app.aavegotchi.com/metadata/aavegotchis/11222"
}
----
