===== Create

`Create` indicates an action of creating new credentials.

When a user creates new credentials, the protocol will convert and record it as Create metadata following the interface below.

===== Interface

[,typescript]
----
interface Create {
    action: string
    profile_id?: string
    address?: string
    handle?: string
    image_uri?: string
    bio?: string
    name?: string
    expiry?: string
    key?: string
    value?: string
}
----

===== Description

|===
| Field          | Description

| `action`       | *Required.* The action of creating new credentials.
| `profile_id`   | *Optional.* The profile ID associated with the new credentials.
| `address`      | *Optional.* The address associated with the new credentials.
| `handle`       | *Optional.* The handle/username associated with the new credentials.
| `image_uri`    | *Optional.* The image URI associated with the new credentials.
| `bio`          | *Optional.* The biography associated with the new credentials.
| `name`         | *Optional.* The name associated with the new credentials.
| `expiry`       | *Optional.* The expiry date associated with the new credentials.
| `key`          | *Optional.* The key associated with the new credentials.
| `value`        | *Optional.* The value associated with the new credentials.
|===

===== Example

[,json]
----
{
    "action": "create",
    "profile_id": "3569",
    "address": "0x3f54953e56a0fe272f3e1e61615bda1fd6578101",
    "handle": "beh.csb",
    "image_uri": "ipfs://bafkreidj4jdpwxi6aiz43ubokv5c3tnqlf4nfpkoss2rysfjzrdetgiekm"
}
----