===== Update

`Update` indicates an action of updating an existing credential.

When a user updates an existing credential, the protocol will convert and record it as Update metadata following the interface below.

===== Interface

[,typescript]
----
interface Update {
    action: string
    profile_id?: string
    address?: string
    handle?: string
    image_uri?: string
    bio?: string
    name?: string
    expiry?: string
    key?: string
    value?: string
}
----

===== Description

|===
| Field          | Description

| `action`       | *Required.* The action of updating an existing credential.
| `profile_id`   | *Optional.* The profile ID associated with the credential being updated.
| `address`      | *Optional.* The address associated with the credential being updated.
| `handle`       | *Optional.* The handle/username associated with the credential being updated.
| `image_uri`    | *Optional.* The image URI associated with the credential being updated.
| `bio`          | *Optional.* The biography associated with the credential being updated.
| `name`         | *Optional.* The name associated with the credential being updated.
| `expiry`       | *Optional.* The expiry date associated with the credential being updated.
| `key`          | *Optional.* The key associated with the credential being updated.
| `value`        | *Optional.* The value associated with the credential being updated.
|===

===== Example

[,json]
----
{
    "action": "update",
    "profile_id": "0x020a73",
    "address": "0xece7eddc02fb8f0010420d0d76911826b1536655",
    "handle": "gupta.lens",
    "image_uri": "ipfs://bafybeih5jwshcxwa73mtfdhwqs2rtevrbhl6t3blrtlb4n5dpea4iqplpu",
    "bio": "I'm trader.",
    "name": "PETE"
}
----