===== Update

`Update` indicates an action of updating an existing credential.

When a user updates an existing credential, the protocol will convert and record it as Update metadata following the interface below.

===== Interface

[,typescript]
----
interface Update {
    action: string
    profile_id?: string
    address?: string
    handle?: string
    image_uri?: string
    bio?: string
    name?: string
    expiry?: string
    key?: string
    value?: string
}
----

===== Description

|===
| Field          | Description

| `action`       | *Required.* The action of updating a new profile.
| `profile_id`   | *Optional.* The updated ID of the profile.
| `address`      | *Optional.* The updated address of the profile.
| `handle`       | *Optional.* The updated handle/username of the profile.
| `image_uri`    | *Optional.* The updated image URI of the profile.
| `bio`          | *Optional.* The updated biography of the profile.
| `name`         | *Optional.* The updated name of the profile.
| `expiry`       | *Optional.* The updated expiry date of the profile.
| `key`          | *Optional.* The updated key of the profile.
| `value`        | *Optional.* The updated value of the profile.
|===

===== Example

[,json]
----
{
    "action": "update",
    "address": "0x76d4ffda8c66864fa07f0a285b8e01e11b4bb7b3",
    "handle": "brinse.lens",
    "image_uri": "https://media.orb.ac/thumbnailDimension768/https://statics-polygon-lens.s3.eu-west-1.amazonaws.com/profile/nft-0x6441543C6537FF430f2e1d6fE8FFFcfc05d52D04_polygon_0x5D666F215a85B87Cb042D59662A7ecd2C8Cc44e6_3097622.gif",
    "name": "Paperhandoooooor",
    "profile_id": "0x01766e"
}
----