===== Update

`Update` indicates an action of updating an existing credential.

When a user updates an existing credential, the protocol will convert and record it as Update metadata following the interface below.

===== Interface

[,typescript]
----
interface Update {
    action: string
    profile_id?: string
    address?: string
    handle?: string
    image_uri?: string
    bio?: string
    name?: string
    expiry?: string
    key?: string
    value?: string
}
----

===== Description

|===
| Field          | Description

| `action`       | *Required.* The action of updating a new profile.
| `profile_id`   | *Optional.* The updated ID of the profile.
| `address`      | *Optional.* The updated address of the profile.
| `handle`       | *Optional.* The updated handle/username of the profile.
| `image_uri`    | *Optional.* The updated image URI of the profile.
| `bio`          | *Optional.* The updated biography of the profile.
| `name`         | *Optional.* The updated name of the profile.
| `expiry`       | *Optional.* The updated expiry date of the profile.
| `key`          | *Optional.* The updated key of the profile.
| `value`        | *Optional.* The updated value of the profile.
|===

===== Example

[,json]
----
{
    "action": "update",
    "profile_id": "0x020a73",
    "address": "0xece7eddc02fb8f0010420d0d76911826b1536655",
    "handle": "gupta.lens",
    "image_uri": "ipfs://bafybeih5jwshcxwa73mtfdhwqs2rtevrbhl6t3blrtlb4n5dpea4iqplpu",
    "bio": "I'm trader.",
    "name": "PETE"
}
----