==== Revoke

`Revoke` indicates an action of removing permissions to token.

===== Interface

[,typescript]
----
interface Revoke {
    action: string;
    address?: string;
    id?: string;
    name?: string;
    standard?: string;
    symbol?: string;
    value: string;
    uri?: string;
    parsed_image_url?: string;
}
----

===== Fields

`action` *Required*:: Action of removing permissions to collectible token, e.g. `revoke`.
`address` *Optional*:: Address of the revoked collectible token, e.g. `0x5452C7fB99D99fAb3Cc1875E9DA9829Cb50F7A13`.
`id` *Optional*:: ID of the revoked collectible token, e.g. `1032`.
`name` *Optional*:: Name of the revoked collectible token, e.g. `The Genesis RSS3 Avatar NFT`.
`standard` *Optional*:: Standard of the revoked collectible token, e.g. `ERC-721`.
`symbol` *Optional*:: Symbol of the revoked collectible token, e.g. `The Genesis RSS3 Avatar NFT`.
`value` *Required*:: Amount of the revoked collectible token, e.g. `1`.
`uri` *Optional*:: URI of the revoked collectible token, e.g. `ipfs://QmdHTECGDf8u4vNe4PLXSqBTBkYqxiCaYYfdJiUhtgiBKR/6`.
`parsed_image_url` *Optional*:: Parsed image URL of the revoked collectible token, e.g. `https://ipfs.io/ipfs/QmSx9QiwjTGKb5m22UscTg3vrbMwUfFsmxVzMH57hkPD5U/1032.png`.

===== Example

[,json]
----
{
    "action": "revoke",
    "address": "0x5452C7fB99D99fAb3Cc1875E9DA9829Cb50F7A13",
    "id": "1032",
    "name": "The Genesis RSS3 Avatar NFT",
    "symbol": "The Genesis RSS3 Avatar NFT",
    "uri": "data:application/json;base64,eyJuYW1lIjogIlRoZSBHZW5lc2lzIFJTUzMgQXZhdGFyIE5GVCAjMTAzMiIsICJkZXNjcmlwdGlvbiI6ICJUaGUgR2VuZXNpcyBSU1MzIEF2YXRhciBORlQgaXMgYSBjb2xsZWN0aW9uIG9mIDEwLDAwMCB1bmlxdWUgYXZhdGFycyBtZXRpY3Vsb3VzbHkgZGVzaWduZWQgdG8gaWRlbnRpZnkgUlNTMyBjb21tdW5pdHkgbWVtYmVycy4iLCAiaW1hZ2UiOiAiaXBmczovL1FtU1g5UWl3alRHQms1bTIyVXNjVGczdnJiTXdVZkZzbXhWek1INTdoa1BENVUvMTAzMi5wbmcifQ==",
    "standard": "ERC-721"
}
----
