==== Revoke

`Revoke` indicates an action of removing permissions to collectible assets.

When a user revokes permissions to collectible assets, the protocol will convert and record it as Revoke metadata following the interface below.

===== Interface

[,typescript]
----
interface Revoke {
    action: string;
    address?: string;
    id?: string;
    name?: string;
    standard?: string;
    symbol?: string;
    value: string;
    uri?: string;
    parsed_image_url?: string;
}
----

===== Description

|===
| Field               | Description

| `action`            | *Required.* The action of removing permissions to collectible assets.
| `address`           | *Optional.* The token address of the revoked collectible assets.
| `id`                | *Optional.* The token ID of the revoked collectible assets.
| `name`              | *Optional.* The token name of the revoked collectible assets.
| `standard`          | *Optional.* The token standard of the revoked collectible assets.
| `symbol`            | *Optional.* The token symbol of the revoked collectible assets.
| `value`             | *Required.* The token amount/value of the revoked collectible assets.
| `uri`               | *Optional.* The token URI of the revoked collectible assets.
| `parsed_image_url`  | *Optional.* The parsed image URL of the revoked collectible assets.
|===

===== Example

[,json]
----
{
    "action": "revoke",
    "address": "0x5452C7fB99D99fAb3Cc1875E9DA9829Cb50F7A13",
    "id": "1032",
    "name": "The Genesis RSS3 Avatar NFT",
    "symbol": "The Genesis RSS3 Avatar NFT",
    "uri": "data:application/json;base64,eyJuYW1lIjogIlRoZSBHZW5lc2lzIFJTUzMgQXZhdGFyIE5GVCAjMTAzMiIsICJkZXNjcmlwdGlvbiI6ICJUaGUgR2VuZXNpcyBSU1MzIEF2YXRhciBORlQgaXMgYSBjb2xsZWN0aW9uIG9mIDEwLDAwMCB1bmlxdWUgYXZhdGFycyBtZXRpY3Vsb3VzbHkgZGVzaWduZWQgdG8gaWRlbnRpZnkgUlNTMyBjb21tdW5pdHkgbWVtYmVycy4iLCAiaW1hZ2UiOiAiaXBmczovL1FtU1g5UWl3alRHQms1bTIyVXNjVGczdnJiTXdVZkZzbXhWek1INTdoa1BENVUvMTAzMi5wbmcifQ==",
    "standard": "ERC-721"
}
----
