==== Appoint

`Appoint` indicates an action of delegating rights to a proxy address.

When a user appoints rights to a proxy address, the protocol will convert and record it as Appoint metadata following the interface below.

===== Interface

[,typescript]
----
interface Appoint {
    action: string
    profile: {
        profile_id?: string
        address?: string
        handle?: string
        image_uri?: string
        bio?: string
        name?: string
        expiry?: string
        key?: string
        value?: string
    }
    proxy_address: string
}
----

===== Description

|===
| Field              | Description

| `action`           | *Required.* The action of appointing rights to a proxy address.
| `profile.profile_id` | *Optional.* The profile ID associated with the appoint action.
| `profile.address`    | *Optional.* The address associated with the appoint action.
| `profile.handle`     | *Optional.* The handle/username associated with the appoint action.
| `profile.image_uri`  | *Optional.* The image URI associated with the appoint action.
| `profile.bio`        | *Optional.* The biography associated with the appoint action.
| `profile.name`       | *Optional.* The name associated with the appoint action.
| `profile.expiry`     | *Optional.* The expiry date associated with the appoint action.
| `profile.key`        | *Optional.* The key associated with the appoint action.
| `profile.value`      | *Optional.* The value associated with the appoint action.
| `proxy_address`     | *Required.* The proxy address to which rights are being delegated.
|===

===== Example

[,json]
----
{
    "action": "appoint",
    "proxy_address": "0xbbc2918c9003d264c25ecae45b44a846702c0e7c",
    "profile": {
        "profile_id": "55544",
        "address": "0x8a6ddc78e3aa24f4f31980623f489a274b305762",
        "handle": "ordi.csb"
    }
}
----