==== Appoint

`Appoint` indicates an action of delegating rights to a proxy account.

When a user appoints rights to a proxy account, the protocol will convert and record it as Appoint metadata following the interface below.

===== Interface

[,typescript]
----
interface Appoint {
    action: string
    profile: {
        profile_id: string
        address: string
        handle: string
        image_uri?: string
        bio?: string
        name?: string
        expiry?: string
        key?: string
        value?: string
    }
    proxy_address: string
}
----

===== Description

|===
| Field              | Description

| `action`           | *Required.* The action of appointing rights to a proxy account.
| `profile.profile_id` | *Required.* The profile ID of the profile.
| `profile.address`    | *Required.* The address of the profile.
| `profile.handle`     | *Required.* The handle/username of the profile.
| `profile.image_uri`  | *Optional.* The image URI of the profile.
| `profile.bio`        | *Optional.* The biography of the profile.
| `profile.name`       | *Optional.* The name of the profile.
| `profile.expiry`     | *Optional.* The expiry date of the profile.
| `profile.key`        | *Optional.* The key of the profile.
| `profile.value`      | *Optional.* The value of the profile.
| `proxy_address`     | *Required.* The proxy address to which the profile'rights are being delegated.
|===

===== Example

[,json]
----
{
    "action": "appoint",
    "proxy_address": "0xbbc2918c9003d264c25ecae45b44a846702c0e7c",
    "profile": {
        "profile_id": "55544",
        "address": "0x8a6ddc78e3aa24f4f31980623f489a274b305762",
        "handle": "ordi.csb"
    }
}
----