==== Remove

`Remove` indicates an action of removing a proxy.

When a user removes a proxy, the protocol will convert and record it as Remove metadata following the interface below.

===== Interface

[,typescript]
----
interface Remove {
    action: string
    profile: {
        profile_id?: string
        address?: string
        handle?: string
        image_uri?: string
        bio?: string
        name?: string
        expiry?: string
        key?: string
        value?: string
    }
    proxy_address: string
}
----

===== Description

|===
| Field              | Description

| `action`           | *Required.* The action of removing a proxy account.
| `profile.profile_id` | *Optional.* The profile ID of the profile.
| `profile.address`    | *Optional.* The address of the profile.
| `profile.handle`     | *Optional.* The handle/username of the profile.
| `profile.image_uri`  | *Optional.* The image URI of the profile.
| `profile.bio`        | *Optional.* The biography of the profile.
| `profile.name`       | *Optional.* The name of the profile.
| `profile.expiry`     | *Optional.* The expiry date of the profile.
| `profile.key`        | *Optional.* The key of the profile.
| `profile.value`      | *Optional.* The value of the profile.
| `proxy_address`     | *Required.* The proxy address to be removed from the profile.
|===

===== Example

[,json]
----
{
    "action": "remove",
    "proxy_address": "0x0f588318a494e4508a121a32b6670b5494ca3357",
    "profile": {
        "profile_id": "32010",
        "address": "0x23c46e912b34c09c4bcc97f4ed7cdd762cee408a",
        "handle": "brucexx.csb"
    }
}
----