==== Remove

`Remove` indicates an action of removing a proxy.

When a user removes a proxy, the protocol will convert and record it as Remove metadata following the interface below.

===== Interface

[,typescript]
----
interface Remove {
    action: string
    profile: {
        profile_id?: string
        address?: string
        handle?: string
        image_uri?: string
        bio?: string
        name?: string
        expiry?: string
        key?: string
        value?: string
    }
    proxy_address: string
}
----

===== Description

|===
| Field              | Description

| `action`           | *Required.* The action of removing a proxy.
| `profile.profile_id` | *Optional.* The profile ID associated with the removal action.
| `profile.address`    | *Optional.* The address associated with the removal action.
| `profile.handle`     | *Optional.* The handle/username associated with the removal action.
| `profile.image_uri`  | *Optional.* The image URI associated with the removal action.
| `profile.bio`        | *Optional.* The biography associated with the removal action.
| `profile.name`       | *Optional.* The name associated with the removal action.
| `profile.expiry`     | *Optional.* The expiry date associated with the removal action.
| `profile.key`        | *Optional.* The key associated with the removal action.
| `profile.value`      | *Optional.* The value associated with the removal action.
| `proxy_address`     | *Required.* The proxy address to be removed.
|===

===== Example

[,json]
----
{
    "action": "remove",
    "proxy_address": "0x0f588318a494e4508a121a32b6670b5494ca3357",
    "profile": {
        "profile_id": "32010",
        "address": "0x23c46e912b34c09c4bcc97f4ed7cdd762cee408a",
        "handle": "brucexx.csb"
    }
}
----