==== Delete

`Delete` indicates an action of deleting a post.

When a user deletes a post, the protocol will convert and record it as Delete metadata following the interface below.

===== Interface

[,typescript]
----
interface Delete {
    handle?: string
    body?: string
    title?: string
    summary?: string
    media?: {
        address: string
        mime_type: string
    }[]
    tags?: string[]
    author_url?: string
    profile_id?: string
    publication_id?: string
    content_uri?: string
    timestamp?: number
}
----

===== Description

|===
| Field           | Description

| `handle`        | *Optional.* The handle/username of the user who is deleting the post.
| `body`          | *Optional.* The main content of the post being deleted.
| `title`         | *Optional.* The title of the post being deleted.
| `summary`       | *Optional.* A short summary of the post being deleted.
| `media`         | *Optional.* An array of media objects that are attached to the post being deleted.
| `media.address` | *Required.* The url/address of the media object.
| `media.mime_type` | *Required.* The mime type of the media object.
| `tags`          | *Optional.* An array of tags that the post being deleted belongs to.
| `author_url`    | *Optional.* The url of the author.
| `profile_id`    | *Optional.* The profile ID of the author.
| `publication_id` | *Optional.* The publication ID of the post being deleted.
| `content_uri`   | *Optional.* The content URI of the post being deleted.
| `timestamp`     | *Optional.* The timestamp of the post being deleted.
|===

===== Example

[,json]
----
{
    "handle": "ordi.csb",
    "title": "YouTube Top100",
    "body": "https://cn.noxinfluencer.com/youtube-channel-rank/top-100-all-all-youtuber-sorted-by-subs-weekly\n\n\n1 T-Series https://www.youtube.com/@tseries\n",
    "profile_id": "55544",
    "publication_id": "7",
    "content_uri": "ipfs://bafkreic7t3twgima3cu54r7ftyuut6h74wpdwtlqoxcd66ox5qtkptokmy"
}s
----