==== Post

`Post` indicates an action of publishing a new post.

When a user publishes a new post, the protocol will convert and record it as Post metadata following the interface below.

===== Interface

[,typescript]
----
interface Post {
    handle?: string
    body?: string
    title?: string
    summary?: string
    media?: {
        address: string
        mime_type: string
    }[]
    tags?: string[]
    author_url?: string
    profile_id?: string
    publication_id?: string
    content_uri?: string
    timestamp?: number
}
----

===== Description

|===
| Field           | Description

| `handle`        | *Optional.* The handle/username of the user who is posting.
| `body`          | *Optional.* The main content of the post.
| `title`         | *Optional.* The title of the post.
| `summary`       | *Optional.* A short summary of the post.
| `media`         | *Optional.* An array of media objects that are attached to the post.
| `media.address` | *Required.* The url/address of the media object.
| `media.mime_type` | *Required.* The mime type of the media object.*
| `tags`          | *Optional.* An array of tags that the post belongs to.
| `author_url`    | *Optional.* The url of the author.
| `profile_id`    | *Optional.* The profile ID of the author.
| `publication_id` | *Optional.* The publication ID of the post.
| `content_uri`   | *Optional.* The content URI of the post.
| `timestamp`     | *Optional.* The timestamp of the post.
|===

===== Example

[,json]
----
{
    "handle": "mstrbstrd.lens",
    "body": "Missed my lens frens :) happy to be back.",
    "media": [
        {
            "address": "ipfs://QmVKY2PnqeeRgtbzPqPuXhJokkV2TmfVeu9kk81fE93UqB",
            "mime_type": "image/jpeg"
        }
    ],
    "profile_id": "0x019c14",
    "publication_id": "0x80",
    "content_uri": "ar://JasdNwPn2LotuM1MjquEiHrEyzpe_a9ejnCtNr3KAIo",
    "tags": [
        "orbpaidcollect"
    ],
    "timestamp": 1699329250
}
----