==== Post

`Post` indicates an action of publishing a new post.

===== Interface

[,typescript]
----
interface Post {
    handle?: string
    body?: string
    title?: string
    summary?: string
    media?: {
        address: string
        mime_type: string
    }[]
    tags?: string[]
    author_url?: string
    profile_id?: string
    publication_id?: string
    content_uri?: string
    timestamp?: number
}
----

===== Fields

`handle` *Optional*:: Handle/username of the user who is posting, e.g. `mstrbstrd.lens`.
`body` *Optional*:: Main content of the post, e.g. `Missed my lens frens :) happy to be back.`.
`title` *Optional*:: The title of the post.
`summary` *Optional*:: Short summary of the post.
`media` *Optional*:: Array of media objects that are attached to the post.
`media.address` *Required*:: Url/address of the media object, e.g. `ipfs://QmVKY2PnqeeRgtbzPqPuXhJokkV2TmfVeu9kk81fE93UqB`.
`media.mime_type` *Required*:: Mime type of the media object, e.g. `image/jpeg`.
`tags` *Optional*:: Array of tags that the post belongs to, e.g. `["orbpaidcollect"]`.
`author_url` *Optional*:: Url of the author.
`profile_id` *Optional*:: Profile ID of the author, e.g. `0x019c14`.
`publication_id` *Optional*:: Publication ID of the post, e.g. `0x80`.
`content_uri` *Optional*:: Content URI of the post, e.g. `ar://JasdNwPn2LotuM1MjquEiHrEyzpe_a9ejnCtNr3KAIo`.
`timestamp` *Optional*:: Timestamp of the post, e.g. `1699329250`.

===== Example

[,json]
----
{
    "handle": "mstrbstrd.lens",
    "body": "Missed my lens frens :) happy to be back.",
    "media": [
        {
            "address": "ipfs://QmVKY2PnqeeRgtbzPqPuXhJokkV2TmfVeu9kk81fE93UqB",
            "mime_type": "image/jpeg"
        }
    ],
    "profile_id": "0x019c14",
    "publication_id": "0x80",
    "content_uri": "ar://JasdNwPn2LotuM1MjquEiHrEyzpe_a9ejnCtNr3KAIo",
    "tags": [
        "orbpaidcollect"
    ],
    "timestamp": 1699329250
}
----