==== Post

`Post` indicates an action of publishing a new post.

When a user publishes a new post, the protocol will convert and record it as Post metadata following the interface below.

===== Interface

[,typescript]
----
interface Post {
    handle?: string
    body?: string
    title?: string
    summary?: string
    media?: {
        address: string
        mime_type: string
    }[]
    tags?: string[]
    author_url?: string
    profile_id?: string
    publication_id?: string
    content_uri?: string
    timestamp?: number
}
----

===== Description

|===
| Field           | Description

| `handle`        | *Optional.* The handle/username of the user who is posting.
| `body`          | *Optional.* The main content of the post.
| `title`         | *Optional.* The title of the post.
| `summary`       | *Optional.* A short summary of the post.
| `media`         | *Optional.* An array of media objects that are attached to the post.
| `media.address` | *Required.* The url/address of the media object.
| `media.mime_type` | *Required.* The mime type of the media object.*
| `tags`          | *Optional.* An array of tags that the post belongs to.
| `author_url`    | *Optional.* The url of the author.
| `profile_id`    | *Optional.* The profile ID of the author.
| `publication_id` | *Optional.* The publication ID of the post.
| `content_uri`   | *Optional.* The content URI of the post.
| `timestamp`     | *Optional.* The timestamp of the post.
|===

===== Example

[,json]
----
{
    "body": "Good morning ",
    "content_uri": "ar://EL2IPR_FUSiw2_7xTL7F9fWS_S9cGY2cJCZb8Map88k",
    "handle": "103786.lens",
    "media": [
    {
        "address": "https://media3.giphy.com/media/JPHUCiioastGw/giphy.gif?cid=236415cd7ky2ps2edkxiuioxr46yvs5j9tfqdm51vv9isyvz&ep=v1_gifs_search&rid=giphy.gif&ct=g",
        "mime_type": "image/gif"
    }
    ],
    "profile_id": "0x010254",
    "publication_id": "0x030e",
    "timestamp": 1712773702
}
----