// Word lists
type AccountPlatform = 'evm' | 'solana' | 'flow' | 'twitter' | 'misskey' | 'jike' | 'playstation' | 'github';
type ItemPlatform = AccountPlatform | 'rss3';
type LinkType = 'following' | 'comment' | 'like' | 'collection' | 'forward';
type AutoAssetType = 'gitcoin_donation' | 'xdai_poap' | 'bsc_nft' | 'ethereum_nft' | 'polygon_nft';
type AutoNoteType = AutoAssetType | 'mirror_entry' | 'twitter_tweet' | 'misskey_note' | 'jike_node';
type ItemAttachmentName = 'thumbnail' | 'main' | 'attributes' | 'full_description';

// Instance
type AccountInstance = string;          // account:${identity}@${AccountPlatform}
type ItemInstance = string;             // ${'asset' | 'note'}:${uniqueID}@${ItemPlatform}    uniqueID: uuid ${chain}-${token_address}-${token_id} ...
type ExternalInstance = string;         // external:${authority}@${scheme}    eg: external:diygod.me%2Fatom.xml@https

type Instance = AccountInstance | ItemInstance | ExternalInstance;

// URI
type InstanceURI = string;              // rss3://${Instance}

type ItemURI = string;                  // ${InstanceURI}/${'note' | 'asset'}/${uuid}
type ItemCustomListURI = string;        // ${InstanceURI}/list/${'notes' | 'assets'}/${index}
type ItemListURI = string;              // ${InstanceURI}/list/${'notes' | 'assets'}

type LinkCustomListURI = string;        // ${InstanceURI | ItemURI}/list/links/${LinkType}/${index}
type LinkListURI = string;              // ${InstanceURI | ItemURI}/list/links/${LinkType}
type BacklinkListURI = string;          // ${InstanceURI}/list/backlinks

type URI = string;                      // Any uri
type URIs = URI[] | URI;                // A series of uris pointing to accessible resources

// Common attributes for each files
interface Base {
    version: 'v0.4.0'; // Proposal version for current file. It should be like `v1.0.0`
    identifier: InstanceURI | ItemCustomListURI | ItemListURI | LinkCustomListURI | LinkListURI | BacklinkListURI;
    date_created: string; // Specifies the created date in RFC 3339 format
    date_updated: string; // Specifies the updated date in RFC 3339 format
}

interface SignedBase extends Base {
    signature: string; // Signed by instance's private key, the signature message is JSON string sorted by key alphabet: `[RSS3] I am confirming the results of changes to my file ${identifier}: JSON.stringify(file, Object.keys(file).sort())`
    agents?: {
        pubkey: string; // A random ed25519 public key generated by the client
        signature: string; // A signature signed by pubkey's private key, the message is the same as `signature`
        app: string; // Name of the app using this agent, eg: Revery
        date_expired: string; // Specifies the expired date in RFC 3339 format
    }[];
}

interface UnsignedBase extends Base {
    auto: true;
}

// Base types
interface Attachment {
    name?: ItemAttachmentName;
    content?: string; // Actual content, mutually exclusive with address
    address?: URIs; // URIs of same resource pointing to third parties, mutually exclusive with content
    mime_type: string; // [MIME type](https://en.wikipedia.org/wiki/Media_type)
    size_in_bytes?: number;
}

interface Metadata {
    proof: string; // transaction, url, etc.
    platform: ItemPlatform;
    from?: string;
    to?: string;
    id: string; // unique id, eg: ${token_address}-${token_id}
}

interface LinksSet {
    identifiers?: {
        type: LinkType;
        identifier_custom: LinkCustomListURI;
        identifier: LinkListURI;
    }[];
    identifier_back: BacklinkListURI;
    filters?: string[];
}

// RSS3 index files, main entrance for a instance
interface Index extends SignedBase, UnsignedBase {
    identifier: InstanceURI;
    controller?: string; // A contract address indicating ownership of the file

    profile?: {
        name?: string;
        avatars?: URIs;
        bio?: string;
        attachments?: Attachment[];

        accounts?: ({
            account: AccountInstance;
            signature?: string; // Signature of `[RSS3] I am adding ${SignableAccount} to my RSS3 instance ${InstanceURI}`
        })[];

        tags?: (AutoAssetType | AutoNoteType | string)[];
        metadata?: Metadata;
    };

    links: LinksSet;

    items: {
        notes: {
            identifier_custom?: ItemCustomListURI;
            identifier: ItemListURI;
            filters?: string[];
        };
        assets: {
            identifier_custom?: ItemCustomListURI;
            identifier: ItemListURI;
            filters?: string[];
        };
    };
}

// items
type Item = {
    identifier: ItemURI;
    date_created: string; // Specifies the published date in RFC 3339 format
    date_updated: string; // Specifies the modified date in RFC 3339 format

    auto?: true; // For auto items
    identifier_instance?: InstanceURI;

    links: LinksSet;

    tags?: (AutoAssetType | AutoNoteType | string)[];
    authors: InstanceURI[];
    title?: string;
    summary?: string;
    attachments?: Attachment[];

    metadata?: Metadata;
};

// RSS3 list files
interface ListBase<URIType, ElementType> {
    identifier: URIType;
    identifier_next?: URIType;
    list?: ElementType[];
}

type ItemPageList = SignedBase & ListBase<ItemCustomListURI, Item>;
type ItemList = UnsignedBase & ListBase<ItemListURI, Item>;

type LinkList = SignedBase & ListBase<LinkListURI, URI>;
type BacklinksList = UnsignedBase & ListBase<BacklinkListURI, InstanceURI | ItemURI>;
