==== Transfer

`Transfer` indicates an action of transferring assets to others.

When a user transfers assets to others, the protocol will convert and record it as Transfer metadata following the interface below.

===== Interface

[,typescript]
----
interface Transfer {
    address?: string;
    id?: string;
    value: string;
    name?: string;
    symbol?: string;
    uri?: string;
    decimals?: number;
    standard?: string;
}
----

===== Description

|===
| Field               | Description

| `address`           | *Optional.* The token address of the transferred assets.
| `id`                | *Optional.* The token ID of the transferred assets.
| `name`              | *Optional.* The token name of the transferred assets.
| `standard`          | *Optional.* The token standard of the transferred assets.
| `symbol`            | *Optional.* The token symbol of the transferred assets.
| `value`             | *Required.* The token amount/value of the transferred assets.
| `uri`               | *Optional.* The token URI of the transferred assets.
| `decimals`          | *Optional.* The token decimals of the transferred assets.
|===

===== Example

[,json]
----
{
    "address": "0x5F82a3967f279729A7C58D741E9824A6d653317E",
    "id": "7",
    "value": "4593020000012345678",
    "name": "xAI",
    "symbol": "xAI",
    "decimals": 8,
    "standard": "ERC-20"
}
----
