==== Revise

`Revise` indicates an action of updating an existing post.

When a user updates an existing post, the protocol will convert and record it as Revise metadata following the interface below.

===== Interface

[,typescript]
----
interface Revise {
    handle: string
    body: string
    title: string
    summary: string
    media: {
        address: string
        mime_type: string
    }[]
    tags: string[]
    author_url: string
    profile_id: string
    publication_id: string
    content_uri: string
    timestamp: number
}
----

===== Description

|===
| Field           | Description

| `handle`        | *Optional.* The handle/username of the user who is revising.
| `body`          | *Optional.* The updated content of the post.
| `title`         | *Optional.* The updated title of the post.
| `summary`       | *Optional.* The updated short summary of the post.
| `media`         | *Optional.* The updated array of media objects that are attached to the post.
| `media.address` | *Required.* The updated url/address of the media object.
| `media.mime_type` | *Required.* The updated mime type of the media object.*
| `tags`          | *Optional.* The updated array of tags that the post belongs to.
| `author_url`    | *Optional.* The url of the author.
| `profile_id`    | *Optional.* The profile ID of the author.
| `publication_id` | *Optional.* The updated publication ID of the post.
| `content_uri`   | *Optional.* The updated content URI of the post.
| `timestamp`     | *Optional.* The updated timestamp of the post.
|===


===== Example

[,json]
----
{
    "handle": "ordi.csb",
    "title": "YouTube Top100",
    "body": "https://cn.noxinfluencer.com/youtube-channel-rank/top-100-all-all-youtuber-sorted-by-subs-weekly\n\n\n1 T-Series https://www.youtube.com/@tseries\n",
    "profile_id": "55544",
    "publication_id": "7",
    "content_uri": "ipfs://bafkreic7t3twgima3cu54r7ftyuut6h74wpdwtlqoxcd66ox5qtkptokmy"
}
----