==== Revise

`Revise` indicates the action of updating an existing post.

===== Interface

[,typescript]
----
interface Revise {
    handle: string
    body: string
    title: string
    summary: string
    media: {
        address: string
        mime_type: string
    }[]
    tags: string[]
    author_url: string
    profile_id: string
    publication_id: string
    content_uri: string
    timestamp: number
}
----

===== Fields

`handle` *Optional*:: Handle/username of the user who is revising, e.g. `ordi.csb`.
`body` *Optional*:: Updated content of the post, e.g. `https://cn.noxinfluencer.com/youtube-channel-rank/top-100-all...`.
`title` *Optional*:: Updated title of the post, e.g. `YouTube Top100`.
`summary` *Optional*:: Updated short summary of the post.
`media` *Optional*:: Updated array of media objects that are attached to the post.
`media.address` *Required*:: Updated url/address of the media object.
`media.mime_type` *Required*:: Updated mime type of the media object.
`tags` *Optional*:: Updated array of tags that the post belongs to.
`author_url` *Optional*:: Url of the author.
`profile_id` *Optional*:: Profile ID of the author, e.g. `55544`.
`publication_id` *Optional*:: Updated publication ID of the post, e.g. `7`.
`content_uri` *Optional*:: Updated content URI of the post, e.g. `ipfs://bafkreic7t3twgima3cu54r7ftyuut6h74wpdwtlqoxcd66ox5qtkptokmy`.
`timestamp` *Optional*:: Updated timestamp of the post.

===== Example

[,json]
----
{
    "handle": "ordi.csb",
    "title": "YouTube Top100",
    "body": "https://cn.noxinfluencer.com/youtube-channel-rank/top-100-all-all-youtuber-sorted-by-subs-weekly\n\n\n1 T-Series https://www.youtube.com/@tseries\n",
    "profile_id": "55544",
    "publication_id": "7",
    "content_uri": "ipfs://bafkreic7t3twgima3cu54r7ftyuut6h74wpdwtlqoxcd66ox5qtkptokmy"
}
----