==== Mint

`Mint` indicates an action of minting a post.

When a user mints a post, the protocol will convert and record it as Mint metadata following the interface below.

===== Interface

[,typescript]
----
interface Mint {
    handle?: string
    body?: string
    title?: string
    summary?: string
    media?: {
        address: string
        mime_type: string
    }[]
    tags?: string[]
    author_url?: string
    profile_id?: string
    publication_id?: string
    content_uri?: string
    timestamp?: number
}
----

===== Description

|===
| Field           | Description

| `handle`        | *Optional.* The handle/username of the user who minted the post.
| `body`          | *Optional.* The main content of the minted post.
| `title`         | *Optional.* The title of tthe minted post.
| `summary`       | *Optional.* A short summary of the minted post.
| `media`         | *Optional.* An array of media objects that are attached to the minted post.
| `media.address` | *Required.* The url/address of the media object.
| `media.mime_type` | *Required.* The mime type of the media object.
| `tags`          | *Optional.* An array of tags that the minted post belongs to.
| `author_url`    | *Optional.* The url of the author.
| `profile_id`    | *Optional.* The profile ID of the author.
| `publication_id` | *Optional.* The publication ID of the minted post.
| `content_uri`   | *Optional.* The content URI of the minted post.
| `timestamp`     | *Optional.* The timestamp of the minted post.
|===

===== Example

[,json]
----
{
    "handle": "henryqw.lens",
    "body": "\"demos\", meaning people, and \"kratos\" meaning power; so democracy can be thought of as \"power of the people\": a way of governing which depends on the will of the people.",
    "profile_id": "0x83a6",
    "publication_id": "0x08",
    "content_uri": "https://arweave.net/aMAYipJXf9rVHnwRYnNF7eUCxBc1zfkaopBt5TJwLWw",
    "timestamp": 1679902646
}
----