==== Mint

`Mint` indicates an action of minting a post.

When a user mints a post, the protocol will convert and record it as Mint metadata following the interface below.

===== Interface

[,typescript]
----
interface Mint {
    handle?: string
    body?: string
    title?: string
    summary?: string
    media?: {
        address: string
        mime_type: string
    }[]
    tags?: string[]
    author_url?: string
    profile_id?: string
    publication_id?: string
    content_uri?: string
    timestamp?: number
}
----

===== Description

|===
| Field           | Description

| `handle`        | *Optional.* The handle/username of the user who minted the post.
| `body`          | *Optional.* The main content of the minted post.
| `title`         | *Optional.* The title of tthe minted post.
| `summary`       | *Optional.* A short summary of the minted post.
| `media`         | *Optional.* An array of media objects that are attached to the minted post.
| `media.address` | *Required.* The url/address of the media object.
| `media.mime_type` | *Required.* The mime type of the media object.
| `tags`          | *Optional.* An array of tags that the minted post belongs to.
| `author_url`    | *Optional.* The url of the author.
| `profile_id`    | *Optional.* The profile ID of the author.
| `publication_id` | *Optional.* The publication ID of the minted post.
| `content_uri`   | *Optional.* The content URI of the minted post.
| `timestamp`     | *Optional.* The timestamp of the minted post.
|===

===== Example

[,json]
----
{
    "body": "💫 **Director Ayaka featured in GQ Japan!**\n\nGQ JAPAN are highlighting Director @lens/ayaka_ohira's work as an animation artist + the upcoming Galverse anime!\n\n📸 Watch it on Instagram: instagram.com/p/C68Ms9NtSci/\n📺 Watch it on TikTok: vt.tiktok.com/ZSYdhUaLw/\n\n_Check it out + like + share ❤️_",
    "content_uri": "ar://K8BiVK02MkWW_Qu4js66mqBwm6ZbLn9mGZaRbuyfyNc",
    "handle": "galverse.lens",
    "media": [
    {
        "address": "ipfs://QmRqN3KTHqaV9mmxotxXa4i1vKFdaYJJPUgUCF8ccMukfP",
        "mime_type": "image/png"
    }
    ],
    "profile_id": "0x01c5b9",
    "publication_id": "0x49",
    "tags": [
    "orbcommunitiesGalverse"
    ],
    "timestamp": 1715724978
}
----